version: '3.9'

services:
  hname:
    container_name: hname
    image: oguzpastirmaci/hostname
    deploy:
      replicas: 5
    expose:
      - 8000
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - hname
    ports:
      - "4000:4000"
      